//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotspotizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hotspotizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Frame.
        /// </summary>
        public static string AddNewFrame {
            get {
                return ResourceManager.GetString("AddNewFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Gesture.
        /// </summary>
        public static string AddNewGesture {
            get {
                return ResourceManager.GetString("AddNewGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Gestures.
        /// </summary>
        public static string AllGestures {
            get {
                return ResourceManager.GetString("AllGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Emulation.
        /// </summary>
        public static string BeginEmulation {
            get {
                return ResourceManager.GetString("BeginEmulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the power and USB connections and restart the application for full functionality..
        /// </summary>
        public static string CheckKinectPowerAndUSB {
            get {
                return ResourceManager.GetString("CheckKinectPowerAndUSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new gesture or load a gesture collection to begin..
        /// </summary>
        public static string CreateGestureOrLoadGestureCollection {
            get {
                return ResourceManager.GetString("CreateGestureOrLoadGestureCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Gesture Collection.
        /// </summary>
        public static string CreateNewGestureCollection {
            get {
                return ResourceManager.GetString("CreateNewGestureCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Frame.
        /// </summary>
        public static string DeleteFrame {
            get {
                return ResourceManager.GetString("DeleteFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Gesture.
        /// </summary>
        public static string DeleteGesture {
            get {
                return ResourceManager.GetString("DeleteGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Gesture from Collection.
        /// </summary>
        public static string DeleteGestureFromCollection {
            get {
                return ResourceManager.GetString("DeleteGestureFromCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the gesture &quot;{0}&quot; from the collection?.
        /// </summary>
        public static string DeleteGestureFromCollectionConfirmation {
            get {
                return ResourceManager.GetString("DeleteGestureFromCollectionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Changes.
        /// </summary>
        public static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to discard the current gesture collection and create a new one?.
        /// </summary>
        public static string DiscardGestureCollectionConfirmation {
            get {
                return ResourceManager.GetString("DiscardGestureCollectionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to download Microsoft Kinect for Windows SDK 1.8 from Microsoft&apos;s website..
        /// </summary>
        public static string DownloadKinectSDK {
            get {
                return ResourceManager.GetString("DownloadKinectSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Gesture.
        /// </summary>
        public static string EditGesture {
            get {
                return ResourceManager.GetString("EditGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front View.
        /// </summary>
        public static string FrontView {
            get {
                return ResourceManager.GetString("FrontView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotspotizer Gesture files (*.hsjson)|*.hsjson.
        /// </summary>
        public static string HotspotizerFileFilter {
            get {
                return ResourceManager.GetString("HotspotizerFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Command.
        /// </summary>
        public static string KeyboardCommand {
            get {
                return ResourceManager.GetString("KeyboardCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not detect a Kinect sensor connected to your computer..
        /// </summary>
        public static string KinectNotDetected {
            get {
                return ResourceManager.GetString("KinectNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Elbow.
        /// </summary>
        public static string LeftElbow {
            get {
                return ResourceManager.GetString("LeftElbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Foot.
        /// </summary>
        public static string LeftFoot {
            get {
                return ResourceManager.GetString("LeftFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Hand.
        /// </summary>
        public static string LeftHand {
            get {
                return ResourceManager.GetString("LeftHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Knee.
        /// </summary>
        public static string LeftKnee {
            get {
                return ResourceManager.GetString("LeftKnee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limb Selection.
        /// </summary>
        public static string LimbSelection {
            get {
                return ResourceManager.GetString("LimbSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Gesture Collection.
        /// </summary>
        public static string LoadGestureCollection {
            get {
                return ResourceManager.GetString("LoadGestureCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Frame Backward.
        /// </summary>
        public static string MoveFrameBackward {
            get {
                return ResourceManager.GetString("MoveFrameBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Frame Forward.
        /// </summary>
        public static string MoveFrameForward {
            get {
                return ResourceManager.GetString("MoveFrameForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Gesture.
        /// </summary>
        public static string NewGesture {
            get {
                return ResourceManager.GetString("NewGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Gesture Collection.
        /// </summary>
        public static string NewGestureCollection {
            get {
                return ResourceManager.GetString("NewGestureCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no gestures in the current gesture collection..
        /// </summary>
        public static string NoGestures {
            get {
                return ResourceManager.GetString("NoGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press key(s) on the keyboard to set the command for this gesture....
        /// </summary>
        public static string PressKeyCombinationForGesture {
            get {
                return ResourceManager.GetString("PressKeyCombinationForGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press/Hold.
        /// </summary>
        public static string PressOrHold {
            get {
                return ResourceManager.GetString("PressOrHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using a &apos;Kinect for Xbox 360&apos; sensor requires the full Microsoft Kinect for Windows SDK 1.8 to be installed on your computer..
        /// </summary>
        public static string RequiredKinectSDK {
            get {
                return ResourceManager.GetString("RequiredKinectSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Elbow.
        /// </summary>
        public static string RightElbow {
            get {
                return ResourceManager.GetString("RightElbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Foot.
        /// </summary>
        public static string RightFoot {
            get {
                return ResourceManager.GetString("RightFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Hand.
        /// </summary>
        public static string RightHand {
            get {
                return ResourceManager.GetString("RightHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Knee.
        /// </summary>
        public static string RightKnee {
            get {
                return ResourceManager.GetString("RightKnee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Gesture.
        /// </summary>
        public static string SaveGesture {
            get {
                return ResourceManager.GetString("SaveGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Gesture Collection.
        /// </summary>
        public static string SaveGestureCollection {
            get {
                return ResourceManager.GetString("SaveGestureCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Next Frame.
        /// </summary>
        public static string SelectNextFrame {
            get {
                return ResourceManager.GetString("SelectNextFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Previous Frame.
        /// </summary>
        public static string SelectPreviousFrame {
            get {
                return ResourceManager.GetString("SelectPreviousFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side View.
        /// </summary>
        public static string SideView {
            get {
                return ResourceManager.GetString("SideView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.microsoft.com/en-us/download/details.aspx?id=40278.
        /// </summary>
        public static string URL_DownloadKinectSDK {
            get {
                return ResourceManager.GetString("URL_DownloadKinectSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizer.
        /// </summary>
        public static string Visualizer {
            get {
                return ResourceManager.GetString("Visualizer", resourceCulture);
            }
        }
    }
}
